### ISSUE TITLE
Crash when opening localhost:3300/docs

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/restroom-mw#14]
With the latest version, _localhost:3300/api/contract_ works fine, while /docs makes it crash and gives this error:

```
TypeError: Cannot create property 'root' on string './zencode'
/home/bario/Desktop/temp/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:287
      throw ex;
      ^

RuntimeError: abort(TypeError: Cannot create property 'root' on string './zencode') at Error
    at jsStackTrace (/home/bario/Desktop/temp/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:2081:17)
    at stackTrace (/home/bario/Desktop/temp/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:2098:16)
    at process.abort (/home/bario/Desktop/temp/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:1853:44)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
    at process.abort (/home/bario/Desktop/temp/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:1859:9)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! restroom-template@1.0.0 start: `node dist/app.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the restroom-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bario/.npm/_logs/2020-10-28T13_30_14_009Z-debug.log
```

**Comment by andrea-dintino** [comment]
You can use this Dockerfile to test: 

```
FROM node:14
RUN npx degit dyne/restroom-template restroom-mw

WORKDIR /restroom-mw

EXPOSE 3300 
EXPOSE 3301 

# Adding a file inline 
RUN touch env.text
RUN echo $'ZENCODE_DIR=/zencode\n\
HTTP_PORT=3300\n\
HTTPS_PORT=3301\n'\
>> /restroom-mw/.env


# Debugging lines
RUN ls -al
RUN cat .env
RUN ls -al ./zencode
RUN cat env.text


run npm i
run npm i fuzzball
run npm run start
```
