### ISSUE TITLE
Test not passing in node v10

### ISSUE THREAD

**Issue by puria** [dyne/restroom-mw#8]
For some reason the db tests are not executed on node 10... this issue here to dig later in the meantime let disable the CI checks on 10.x family.

The error is 
```
 ✔ db › tests › index › Middleware db should exists (243ms)
 .  System memory manager in use
 .  ECDH curve is SECP256K1
 .  Memory in use: 221 KB
[*] Zenroom teardown.
 .  Memory used: 247 KB
 .  System memory manager in use
 .  ECDH curve is SECP256K1
 .  Memory in use: 221 KB
[*] Zenroom teardown.
 .  Memory used: 247 KB
Executing (default): CREATE TABLE IF NOT EXISTS `results` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `result` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): INSERT INTO `tablename` (`id`,`result`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3);
Executing (default): PRAGMA INDEX_LIST(`results`)
Executing (default): INSERT INTO `results` (`id`,`result`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3);
SyntaxError: Unexpected token { in JSON at position 246
SyntaxError: Unexpected token { in JSON at position 246

  Uncaught exception in packages/db/tests/index.js

  RuntimeError: abort(SyntaxError: Unexpected token { in JSON at position 246) at Error: 

  › jsStackTrace (node_modules/zenroom/dist/lib/zenroom.js:2081:17)
  › stackTrace (node_modules/zenroom/dist/lib/zenroom.js:2098:16)
  › process.abort (node_modules/zenroom/dist/lib/zenroom.js:1853:44)
  › processEmit [as emit] (node_modules/signal-exit/index.js:161:32)
  › emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
  › process._tickCallback (internal/process/next_tick.js:69:34)
  › process.abort (node_modules/zenroom/dist/lib/zenroom.js:1859:9)
  › processEmit [as emit] (node_modules/signal-exit/index.js:161:32)
  › emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
  › process._tickCallback (internal/process/next_tick.js:69:34)

/Users/puria/src/github.com/dyne/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:287
      throw ex;
      ^

RuntimeError: abort(SyntaxError: Unexpected token { in JSON at position 246) at Error: 
    at jsStackTrace (/Users/puria/src/github.com/dyne/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:2081:17)
    at stackTrace (/Users/puria/src/github.com/dyne/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:2098:16)
    at process.abort (/Users/puria/src/github.com/dyne/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:1853:44)
    at process.emit (events.js:203:15)
    at processEmit [as emit] (/Users/puria/src/github.com/dyne/restroom-mw/node_modules/signal-exit/index.js:161:32)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
    at process.abort (/Users/puria/src/github.com/dyne/restroom-mw/node_modules/zenroom/dist/lib/zenroom.js:1859:9)
    at process.emit (events.js:203:15)
    at processEmit [as emit] (/Users/puria/src/github.com/dyne/restroom-mw/node_modules/signal-exit/index.js:161:32)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
  ✖ packages/db/tests/index.js exited with a non-zero exit code: 7
  ─
```

**Comment by puria** [comment]
Was fixed in the latest commits
